### ISSUE TITLE
The project name

### ISSUE THREAD

**Issue by 1995parham** [mmsamiei/bavand-scraper#1]
Where the name of the project comes from? 😄

**Comment by mmsamiei** [comment]
آه آقای الوانی، دلمون تنگ شده برات ، هیچ گونه راه ارتباطی هم که باهات نداریم :( سخت در این روزهای تیره و تار دلتنگت هستیم کجایی شما؟ :(

**Comment by 1995parham** [comment]
من که اسنپ هستم دانشکده هم میرم. میل بزن بزرگ مرد
حالا نگفتی چرا باوند؟
